name: Containerized C Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    # Forces the job to run inside a clean, modern Alpine Linux container
    container:
      image: alpine:latest

    steps:
      - name: Install Build Essentials
        run: apk add --no-cache gcc musl-dev git

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile and Run Code
        run: |
          gcc main.c -o greeting
          echo "Yogesh" | ./greeting


